### ISSUE TITLE
lmnn for classification

### ISSUE THREAD

**Issue by yangyumo** [metric-learn/metric-learn#106]
Can you provide a predictive function

**Comment by wdevazelhes** [comment]
Hi, in order to use `LMNN` for prediction, you can build a scikit-learn [pipeline](http://scikit-learn.org/stable/modules/pipeline.html#pipeline) with a k-nearest neighbors classifier, this way: `classifier = make_pipeline(LMNN(), KNeighborsClassifier())`. Here is a working minimal example. 
```python
from metric_learn import LMNN
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import make_pipeline
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score, train_test_split

X, y = make_classification()
X_train, X_test, y_train, y_test = train_test_split(X, y)
clf = make_pipeline(LMNN(), KNeighborsClassifier())
clf.fit(X_train, y_train)
clf.predict(X_test)
```
Indeed, metric-learn's `LMNN` is a `Transformer` and here it will embed points in a space where similar points (from the same class) are closer to each other and dissimilar points are further away.  Then the knn algorithm will classify the points based on neighbors in the new embedding space.

**Comment by yangyumo** [comment]
First of all, I would like to thank you for your timely answer to my question.

Secondly, If I use LFDA() to calculate distance, can I use the above code to implement KNN classification?
eg:
X, y = make_classification()
X_train, X_test, y_train, y_test = train_test_split(X, y)
clf = make_pipeline(LFDA(), KNeighborsClassifier())
clf.fit(X_train, y_train)
clf.predict(X_test)

I think your code about metric-learn's LMNN can use other method in metric-learn package, so I tried the LFDA to calculate distance. But I get those result. I have no idea about this result. 
If metri-learn's LMNN can be used in pipeline, why have it those result? 

The result:
I use the code about LFDA, I get the error that is 
"LinAlgError: the leading minor of order 5 of 'b' is not positive definite. The factorization of 'b' could not be completed and no eigenvalues or eigenvectors were computed.
".
I think the reason is that the dataset is not positive definite, so I tried other dataset.
eg:
from sklearn.datasets import load_iris
iris_data = load_iris()
X = iris_data['data']
y = iris_data['target']
X_train, X_test, y_train, y_test = train_test_split(X, y)
clf = make_pipeline(LFDA(), KNeighborsClassifier())
clf.fit(X_train, y_train)
clf.predict(X_test)

 but I get this result. The result are as follows: 

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-20-82d0ac793034> in <module>()
      6 
      7 clf = make_pipeline(LFDA(), KNeighborsClassifier())
----> 8 clf.fit(X_train, y_train)
      9 clf.predict(X_test)

~/anaconda3/lib/python3.6/site-packages/sklearn/pipeline.py in fit(self, X, y, **fit_params)
    246             This estimator
    247         """
--> 248         Xt, fit_params = self._fit(X, y, **fit_params)
    249         if self._final_estimator is not None:
    250             self._final_estimator.fit(Xt, y, **fit_params)

~/anaconda3/lib/python3.6/site-packages/sklearn/pipeline.py in _fit(self, X, y, **fit_params)
    211                 Xt, fitted_transformer = fit_transform_one_cached(
    212                     cloned_transformer, None, Xt, y,
--> 213                     **fit_params_steps[name])
    214                 # Replace the transformer of the step with the fitted
    215                 # transformer. This is necessary when loading the transformer

~/anaconda3/lib/python3.6/site-packages/sklearn/externals/joblib/memory.py in __call__(self, *args, **kwargs)
    360 
    361     def __call__(self, *args, **kwargs):
--> 362         return self.func(*args, **kwargs)
    363 
    364     def call_and_shelve(self, *args, **kwargs):

~/anaconda3/lib/python3.6/site-packages/sklearn/pipeline.py in _fit_transform_one(transformer, weight, X, y, **fit_params)
    581         res = transformer.fit_transform(X, y, **fit_params)
    582     else:
--> 583         res = transformer.fit(X, y, **fit_params).transform(X)
    584     # if we have a weight for this transformer, multiply output
    585     if weight is None:

~/anaconda3/lib/python3.6/site-packages/metric_learn/lfda.py in fit(self, X, Y)
     68      Y: (n,) array-like of class labels
     69     '''
---> 70     X, Y, num_classes, n, d = self._process_inputs(X, Y)
     71     tSb = np.zeros((d,d))
     72     tSw = np.zeros((d,d))

~/anaconda3/lib/python3.6/site-packages/metric_learn/lfda.py in _process_inputs(self, X, Y)
     59 
     60     if not 0 < self.params['k'] < d:
---> 61       raise ValueError('Invalid k, must be in [0,%d]' % (d-1))
     62 
     63     return X, Y, num_classes, n, d

ValueError: Invalid k, must be in [0,3]

**Comment by wdevazelhes** [comment]
Thanks for providing code snippets and reporting those errors. Note that you can improve readability of the message using code blocks github syntax, using ` ```python ` for python code and ` ```pytb ` for output traceback. (see [here](https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting))

A priori, for your classification problem you should be able to use any algorithm that take as input points and classes, namely `LMNN`, `LFDA` and `NCA`.

Therefore the snippets you provided should normally run without errors... 

I tried to reproduce them, and for me the `make_classification` example works some times but for instance with random seed 7 for `train_test_split` it does not work... I will open an issue for that. However, the `load_iris` example works for me. Looking into your error message I suspect it might be due to a `scipy` version problem. My configuration is : 
```
Linux-4.4.0-131-generic-x86_64-with-debian-stretch-sid
Python 3.4.5 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:47:47) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
NumPy 1.15.0
SciPy 1.1.0
Scikit-Learn 0.19.2
Metric-Learn from master
```

Could you provide your versions of libraries by running the following snippet on your machine and pasting the output ? 

```python
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import numpy; print("NumPy", numpy.__version__)
import scipy; print("SciPy", scipy.__version__)
import sklearn; print("Scikit-Learn", sklearn.__version__)
```

Also, which version of metric-learn do you use ? The one from pip install ? You can find the version number with `pip show metric-learn`.

If you don't necessary want to use `LFDA`, I would encourage you to stick to `LFDA` and/or try out `NCA` until the issues are resolved for `LFDA`. 

I hope this helps.

**Comment by yangyumo** [comment]
Thanks for your response and remind.
```
platform: Darwin-17.7.0-x86_64-i386-64bit
sys: Python 3.6.5 |Anaconda, Inc.| (default, Apr 26 2018, 08:42:37) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
numpy: NumPy 1.14.3
scipy: SciPy 1.1.0
sklearn: Scikit-Learn 0.19.1
metric-learn: Version: 0.3.0



```
my pc is MacBook Pro (Retina, 15-inch, Mid 2015), the system is macOS High Sierra and version is 10.13.6. Thanks!

**Comment by wdevazelhes** [comment]
Thanks for your informations. After investigating, the latest release (v0.3.0, which you have), was too restrictive on the format of input than the master version (throwing the error `ValueError: Invalid k, must be in [0,3]`) . You could install ``metric-learn`` from source, where this problem is solved in master, and it should solve the problem with `load_iris`. 
You can that with  `pip install git+https://github.com/metric-learn/metric-learn`
