### ISSUE TITLE
MMC: w_previous referenced before assignment

### ISSUE THREAD

**Issue by shalan12** [metric-learn/metric-learn#74]
While running MMC with diagonal set to True, I get the following error.

mmc.py, line 277 in fit_diag_ 
UnboundLocalError: local variable 'w_previous' referenced before assignment.

**Comment by perimosocordiae** [comment]
Interesting. This is probably indicating that your objective value is NaN, because `w_previous` will only be undefined when `obj < obj * 1.1`:
https://github.com/all-umass/metric-learn/blob/84dbcbef3896e62b664dbbdf83fa673d4976ec40/metric_learn/mmc.py#L266

In any case, we should fix the code to raise a more informative error here.

**Comment by kpriyadarshini** [comment]
In MMC code, if the projection of 1 and 2 failed,  or obj <= obj_previous due to projection of 1 and 2, the matrix A is moved in the direction of the gradient of similarity constraint whereas in another case it is moved in the direction of the gradient of dissimilarity constraint.

Isn't it moved always in the gradient of dissimilarity constraint?
Thanks for help

**Comment by wdevazelhes** [comment]
@shalan12 Thanks for reporting this error. I agree with @perimosocordiae that something is wrong with the objective. Could you provide a minimal example to reproduce the error ? 

@kpriyadarshini you are referring to the full case right ? (the one with projections is the full case) When you say "in another case", do you mean another "if" case within the full case, or do you refer to the diagonal case ? Looking at the code I have the impression that for the full case, in any case we are moving in the normalized direction of the gradient of the dissimilarity constraint projected on the orthogonal subspace of the gradient of the similarity constraint. This is similar to the paper (http://ai.stanford.edu/~ang/papers/nips02-metric.pdf, at the top of page 4, figure 1, and note 5 at bottom of page) (although I'm not sure why this direction needs to be normalized: I did not find any mention of this in the paper).
If you were comparing the full case and the diagonal case, maybe note this: while the full case **maximizes the dissimilarity constraint** (under inequalities constraints including the similarity constraint), the diagonal case **minimizes the similarity constraint** minus the log of the dissimilarity constraints function. (see the paper)
These are two equivalent views of the same problem: trying to maximize distances between dissimilar samples and minimize distances between similar samples.
I hope this answers your question: tell me if I missed something here

**Comment by bellet** [comment]
`obj >= obj * 1.1` can also hold when `w` is the zero vector (which is a valid solution / initialization). Using addition instead of multiplication to initialize `obj_previous` would fix this. Regarding NaN, one should probably raise a specific error.

**Comment by wdevazelhes** [comment]
> obj >= obj * 1.1 can also hold when w is the zero vector (which is a valid solution / initialization). 

@bellet I agree, and it can also happen when `obj` is negative, which can happen in practice if dissimilar points are very close to each other (because then `_D_objective` will be very negative since:

https://github.com/metric-learn/metric-learn/blob/84dbcbef3896e62b664dbbdf83fa673d4976ec40/metric_learn/mmc.py#L337-L338

And therefore this term could be negative:

https://github.com/metric-learn/metric-learn/blob/84dbcbef3896e62b664dbbdf83fa673d4976ec40/metric_learn/mmc.py#L265)

Here is a small example where this happens: 
```python
import numpy as np
from metric_learn import MMC

X = np.array([[0, 0.1], [0, 0.1001], [1, 1], [2, 2]])
a, b, c, d = np.array([2]), np.array([3]), np.array([0]), np.array([1])

mmc = MMC(diagonal=True)
mmc.fit(X, [a, b, c, d])
```
Returns: 
```pytb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/will/Code/metric-learn-bis/metric_learn/mmc.py", line 74, in fit
    return self._fit_diag(X, constraints)
  File "/home/will/Code/metric-learn-bis/metric_learn/mmc.py", line 276, in _fit_diag
    w[:] = w_previous
UnboundLocalError: local variable 'w_previous' referenced before assignment
```
> Using addition instead of multiplication to initialize obj_previous would fix this

Agreed, I'll submit a PR to fix this using addition rather than multiplication

> Regarding NaN, one should probably raise a specific error.

Agreed, I'll include a check of finiteness in the PR
